name: testmephysics
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  rflutter_alert: ^1.1.0
  material_design_icons_flutter: ^4.0.5655
  flutter_markdown: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  
  fonts:
    - family: pacifico
      fonts:
        - asset: lib/fonts/Pacifico-Regular.ttf
  assets:
    - lib/assets/
  
  
  
  
  
  
  
  
  
